name: Tests Windows

on:
  push:
  pull_request:
    
jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v2
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel flex bison gcc make diffutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-ca-certificates
    
    - name: Build Virus Macrophage project
      run: |
        make virus-macrophage-sample
        make
        
    - name: Run Virus Macrophage cell lines project
      run: |
        .\\virus-sample.exe
        
    - name: Build PhysiBoSS cell lines project
      run: |
        make reset
        make physiboss-cell-lines-sample
        make clean
        make 
      
    - name: Run PhysiBoSS cell lines project
      run: |
        .\\PhysiBoSS_Cell_Lines.exe
        
    - name: Build PhysiMeSS project
      run: |
        make reset
        make physimess-sample
        make clean
        make
        
    - name: Run PhysiMeSS project
      run: |
        .\\project
        .\\project config\\Fibre_Initialisation\\mymodel_initialisation.xml
        .\\project config\\Cell_Fibre_Mechanics\\mymodel_rotating.xml
        
  build_physiboss_tutorial:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v2
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel flex bison gcc make diffutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-ca-certificates
    
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make
        
    - name: Run PhysiBoSS tutorial
      run: |
        .\\project.exe config\\cell_cycle\\PhysiCell_settings_cell_cycle_2D.xml
        .\\project.exe config\\simple_tnf\\4_mutants.xml
        .\\project.exe config\\differentiation\\PhysiCell_settings_2D_diff.xml
        
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_windows
        path: project.exe
