name: Tests MacOSX M1

on:
  push:
  pull_request:
    
jobs:
  
  build_physiboss_tutorial:
    runs-on: flyci-macos-large-latest-m1

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@13
      
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make clean
        make PHYSICELL_CPP=g++-13
        
    - name: Run PhysiBoSS tutorial
      run: |
        ./project config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        
    - name: Look at the generated binary
      run: |
        otool -L project
        lipo -archs project 
      
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_macosx_m1
        path: project