name: Tests Windows

on:
  push:
  pull_request:
    
jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel flex bison gcc make diffutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-ca-certificates
    
    - name: Build Virus Macrophage project
      run: |
        make virus-macrophage-sample
        make
        
    - name: Run Virus Macrophage cell lines project
      run: |
        .\\virus-sample.exe
    
  build_physiboss:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel flex bison gcc make diffutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-ca-certificates
         
    - name: Build PhysiBoSS cell lines project
      run: |
        make reset
        make physiboss-cell-lines-sample
        make clean
        make 
      
    - name: Run PhysiBoSS cell lines project
      run: |
        .\\PhysiBoSS_Cell_Lines.exe
        
    - name: Build PhysiMeSS project
      run: |
        make reset
        make physimess-sample
        make clean
        make
        
    - name: Run PhysiMeSS project
      run: |
        .\\project
        .\\project config\\Fibre_Initialisation\\mymodel_initialisation.xml
        .\\project config\\Cell_Fibre_Mechanics\\mymodel_rotating.xml
        
      
    - name: Build PhysiBoSS TNF project
      run: |
        make reset
        make physiboss-tnf-model
        make clean
        make 
      
    - name: Run PhysiBoSS TNF project
      run: |
        .\\spheroid_TNF_model
