name: Tests Ubuntu

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get install flex bison
      
    - name: Build Virus Macrophage project
      run: |
        make virus-macrophage-sample
        make
        
    - name: Run Virus Macrophage cell lines project
      run: |
        ./virus-sample
        
  build_physimess:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get install flex bison
      
    - name: Build PhysiMeSS project
      run: |
        make physimess-sample
        make
        
    - name: Run PhysiMeSS project
      run: |
        ./project
        ./project config/Fibre_Initialisation/mymodel_initialisation.xml
        ./project config/Cell_Fibre_Mechanics/mymodel_rotating.xml
        
  build_physiboss_cell_lines:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get install flex bison
  
    - name: Build PhysiBoSS cell lines project
      run: |
        make physiboss-cell-lines-sample
        make clean
        make
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines

  build_physiboss_TNF:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get install flex bison
  
    - name: Build PhysiBoSS tnf model
      run: |
        make physiboss-tnf-model
        make clean
        make
        
    - name: Run PhysiBoSS TNF project
      run: |
        ./spheroid_TNF_model
        
         
  build_physiboss_tutorial:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make static STATIC_OPENMP=/usr/lib/gcc/x86_64-linux-gnu/11/libgomp.a
        ldd project
        
    - name: Run PhysiBoSS tutorial
      run: |
        ./project config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: tutorial_binary_linux
        path: project

    
  build_physiboss_cancer_invasion:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build PhysiBoSS Cancer Invasion
      run: |
        make physiboss-tutorial-invasion
        make static STATIC_OPENMP=/usr/lib/gcc/x86_64-linux-gnu/11/libgomp.a
        ldd invasion_model
        
    - name: Run PhysiBoSS cancer invasion
      run: |
        ./invasion_model config/PhysiCell_settings_2D.xml
        
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: invasion_model_binary_linux
        path: invasion_model
