name: Tests Ubuntu

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install flex bison
      
    - name: Build Virus Macrophage project
      run: |
        make virus-macrophage-sample
        make
        
    - name: Run Virus Macrophage cell lines project
      run: |
        ./virus-sample
        
    - name: Build PhysiBoSS cell lines project
      run: |
        make reset
        make physiboss-cell-lines-sample
        make clean
        make
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines
        
    
  build_physiboss_tutorial:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install flex bison
      
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make
        
    - name: Run PhysiBoSS tutorial
      run: |
        ./project config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        ./project config/simple_tnf/4_mutants.xml
        ./project config/differentiation/PhysiCell_settings_2D_diff.xml
        
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_linux
        path: project