name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
  build_virus_macrophage:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@10

    - name: Build Virus Macrophage project
      run: |
        make virus-macrophage-sample
        make PHYSICELL_CPP=g++-10
        
    - name: Run Virus Macrophage cell lines project
      run: |
        ./virus-sample


  build_physiboss_cell_lines:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@11
      
    - name: Build PhysiBoSS cell lines project
      run: |
        make physiboss-cell-lines-sample
        make clean
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines
  
  build_physimess:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@11
      
    - name: Build PhysiMeSS project
      run: |
        make physimess-sample
        make clean
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiMeSS project
      run: |
        ./project
        ./project config/Fibre_Initialisation/mymodel_initialisation.xml
        ./project config/Cell_Fibre_Mechanics/mymodel_rotating.xml
        
       
  
  build_physiboss_tutorial:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@11
      
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make clean
        make PHYSICELL_CPP=g++-11
        cp project project_macos11

    - name: Run PhysiBoSS tutorial
      run: |
        ./project config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        ./project config/differentiation/PhysiCell_settings_2D_diff.xml
       
    - name: Caching produced project binary 
      uses: actions/cache@v3
      with:
        path: |
          /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/project_macos11
        key: ${{ runner.os }}-macos11-project-${{ github.run_id }}
    
    - name: Look at the generated binary
      run: |
        otool -L project
        lipo -archs project           
       
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_macosx_macos11
        path: project
        
    
  build_physiboss_tutorial_macos12:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@12
      
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make clean
        make PHYSICELL_CPP=g++-12
        cp project project_macos12

    - name: Run PhysiBoSS tutorial
      run: |
        ./project config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        ./project config/differentiation/PhysiCell_settings_2D_diff.xml
    
    - name: Caching produced project binary 
      uses: actions/cache@v3
      with:
        path: |
          /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/project_macos12
        key: ${{ runner.os }}-macos12-project-${{ github.run_id }}
    
    - name: Look at the generated binary
      run: |
        otool -L project
        lipo -archs project          
    
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_macosx_macos12
        path: project
        
    
  build_physiboss_tutorial_macos13:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@13
      
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make clean
        make PHYSICELL_CPP=g++-13
        cp project project_macos13

    - name: Run PhysiBoSS tutorial
      run: |
        ./project config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        ./project config/differentiation/PhysiCell_settings_2D_diff.xml
    
    - name: Caching produced project binary 
      uses: actions/cache@v3
      with:
        path: |
          /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/project_macos13
        key: ${{ runner.os }}-macos13-project-${{ github.run_id }}
    
    - name: Look at the generated binary
      run: |
        otool -L project
        lipo -archs project      
    
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_macosx_macos13
        path: project

  build_physiboss_tutorial_m1:
    runs-on: flyci-macos-large-latest-m1

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@13
      
    - name: Build PhysiBoSS tutorial
      run: |
        make physiboss-tutorial
        make clean
        make PHYSICELL_CPP=g++-13
        cp project project_macosm1

    - name: Run PhysiBoSS tutorial
      run: |
        ./project config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        ls -al /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/
        ls -al /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/project_macosm1
        
    - name: Caching produced project binary 
      uses: actions/cache@v3
      with:
        path: |
          /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/project_macosm1
        key: ${{ runner.os }}-macosm1-project-${{ github.run_id }}
     
    - name: Look at the generated binary
      run: |
        otool -L project
        lipo -archs project 
      
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_macos_m1
        path: project
        
  build_physiboss_tutorial_universal:
    runs-on: macos-13
    needs: [build_physiboss_tutorial_m1, build_physiboss_tutorial_macos13]

    steps:
    - uses: actions/checkout@v4

    - name: Caching produced project binary 
      uses: actions/cache@v3
      with:
        path: |
          /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/project_macosm1
        key: ${{ runner.os }}-macosm1-project-${{ github.run_id }}
    
    - name: Caching produced project binary 
      uses: actions/cache@v3
      with:
        path: |
          /Users/runner/work/PhysiBoSSv2/PhysiBoSSv2/project_macos13
        key: ${{ runner.os }}-macos13-project-${{ github.run_id }}
    
    - name: Looking at caches binaries
      run: |
        ls 
        lipo -archs project_macos13
        lipo -archs project_macosm1
        lipo -create -output project_macos13 project_macosm1 project_macos_universal
        lipo -archs project_macos_universal
        
    - name: Run PhysiBoSS tutorial
      run: |
        ./project_macos_universal config/cell_cycle/PhysiCell_settings_cell_cycle_2D.xml
        ./project_macos_universal config/differentiation/PhysiCell_settings_2D_diff.xml

    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: tutorial_binary_macosx_universal
        path: project_macos_universal
        
    